#config/application.yml

AWS-ACCESS_KEY: "AKIA5VRSWNEKNUO67NDQ"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "tiacodesflixter"
AWS_REGION: "us-east-1"

SECRET_KEY: 'sk_test_OiKHGhAkpCHGXAlMiuE9rNMg00wamSwo7T'
PUBLISHABLE_KEY: 'pk_test_85xnMDHgkHLuOPYbG8TMq1JY00MsRSEtGD'