#config/application.yml

AWS-ACCESS_KEY: "AKIA5VRSWNEKKPFWS2NS"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "tmcodes0513"
AWS_REGION: "us-east-1"
SECRET_KEY: 'sk_test_OiKHGhAkpCHGXAlMiuE9rNMg00wamSwo7T'
PUBLISHABLE_KEY: 'pk_test_85xnMDHgkHLuOPYbG8TMq1JY00MsRSEtGD'