#config/application.yml

AWS-ACCESS_KEY: "AKIA5VRSWNEKDJLJTMVL"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "tmcodesflixter"
AWS_REGION: "us-east-1"


SECRET_KEY: 'sk_test_OiKHGhAkpCHGXAlMiuE9rNMg00wamSwo7T'
PUBLISHABLE_KEY: 'pk_test_85xnMDHgkHLuOPYbG8TMq1JY00MsRSEtGD'