#config/application.yml

AWS-ACCESS_KEY: "AKIAINTQWREBAKRN6WKQ"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "tmcodeflixter"
AWS_REGION: "us-east-1"


SECRET_KEY: 'sk_test_OiKHGhAkpCHGXAlMiuE9rNMg00wamSwo7T'
PUBLISHABLE_KEY: 'pk_test_85xnMDHgkHLuOPYbG8TMq1JY00MsRSEtGD'