#config/application.yml

AWS-ACCESS_KEY: "AKIA5VRSWNEKGEL4KZUN"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "tmcodeflixter"
AWS_REGION: "us-east-1"


SECRET_KEY: 'sk_test_OiKHGhAkpCHGXAlMiuE9rNMg00wamSwo7T'
PUBLISHABLE_KEY: 'pk_test_85xnMDHgkHLuOPYbG8TMq1JY00MsRSEtGD'